### ISSUE TITLE
Time entry cut off if still running (via Zapier)

### ISSUE THREAD

**Issue by rockethouse** [timecamp/timecamp-api#14]
Hi,

I have tried both using a custom script and the javascript api wrapper as well as Zapier and have found an issue where if a timer is still running when Zapier tries to run an update, it will stop the time  and only import half of it. Then the left over time is lost!

How can this be fixed?

**Comment by rockethouse** [comment]
EDIT: I can now see whats happening.

It appears time entries get updated after the timer has stopped... it's visible in the "last_modify" field... the records I have pulled in my database are different then what are being seen in the API.

Is there any way to get access to time entries that are FINAL before pulling them from the API? This essentially makes it useless at the moment.

**Comment by timecamp** [comment]
Sorry at this moment not :(
