### ISSUE TITLE
Date time zone

### ISSUE THREAD

**Issue by maxguru** [timecamp/timecamp-api#15]
When working with the API, what time zone should I assume for the dates?

Is it possible to filter time entries based on the `last_modify` field?  Is this what `GET /entries_changes` does?

**Comment by maxguru** [comment]
@timecamp, any ideas?

**Comment by maxguru** [comment]
So looks like TimeCamp stores and displays whatever time the browser shows to the user that created the time entry.  So, another user in a different time zone will see the same time stamps as the original user!  What kind of self respecting time tracking tool doesn't have the concept of time zones?!?

**Comment by widget102** [comment]
Unfortunately you are right :( We will soon have private alpha for new Timecamp written from scratch that have full timezone support, but meanwhile we can't help with timezone issue.

About filtering changes by last_modify it's not possible. `/entries_changes` sends only information about entry history (audit log)

**Comment by widget102** [comment]
Can I ask what are you trying to accomplish?

**Comment by maxguru** [comment]
I am trying to sync data (time entries and tasks) with another API.  It would really help if the API allowed to query for changes between two timestamps or to get only the changes since the last sync.  It would be even better if the API provided some sort of push notifications feature using either WebSockets or something else.
