### ISSUE TITLE
Tasks GET is an object?

### ISSUE THREAD

**Issue by kulbida** [timecamp/timecamp-api#16]
Hi Gents,
I'm working on some utility routine and heavily utilize this API. When is embarrassing to me is why output for GET `tasks` is not an array but instead an JSON object with key as task_id and value been task object itself? This makes API hard to work with especially when you use statically typing language. On the other hand, GET `users` works as expected, returning an Array of users. So please, be consistent with your API and please change end point for `tasks` to return Array as well. Thanks!

**Comment by timecamp** [comment]
Yeah, you are right :(, but as we talked before we don't have versioning yet, and we don't want to change this at this point @kulbida
