### ISSUE TITLE
Inconsistent POST/PUT behaviour 

### ISSUE THREAD

**Issue by BeardedSteve** [timecamp/timecamp-api#2]
According to this documentation, the **POST** and **PUT** behaviour seems to change between item types. Items _invoices_/_clients_ use **PUT** to create and **POST** to update, other items such as _tasks_ use the reverse behaviour.

This is pretty confusing. Is it an option to consistently use **PUT**, **POST** and **PATCH** as described in [RFC2616 Section 9](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5)?

**Comment by SteveFlexsis** [comment]
Actually **PATCH** is probably to be avoided for now. Consistent **PUT** and **POST** would be nicer though I think.

**Comment by timecamp2** [comment]
Yes, you are totally right. We are planning to release new verion of our API, and definitly we will keep an eye on this basic issue. Thanks.
