### ISSUE TITLE
Add activity is confusing

### ISSUE THREAD

**Issue by CurlyBraceTT** [timecamp/timecamp-api#21]
Hey, I am bulding C# lib around your API.

I am trying to add activity via post method:
https://github.com/timecamp/timecamp-api/blob/master/sections/computer-activities.md

The response is 
`"You must provide activity with user_id, application_id, end_date, end_time, task_id to change activity task"`
This error doesn't correlates with the doc parameters at all.

So what I should send?

**Comment by jzabroski** [comment]
Hi @CurlyBraceTT 

I also built a C# lib using RestSharp and QuickType.Io - can we compare notes?

I built mine for  a client, so doubt I can open source it, but I can try.

**Comment by timecamp** [comment]
Hi, sorry for late response, we will work on this

**Comment by timecamp** [comment]
Hello, this issue is pretty old, we will close it. But if it is still happening, please reopen.

**Comment by jzabroski** [comment]
@timecamp  You guys have THE WORST customer service.
