### ISSUE TITLE
/tasks returns an empty array for user_ids instead of an empty object

### ISSUE THREAD

**Issue by kiasyn** [timecamp/timecamp-api#22]
On a result with user ids it will return
```
{
"123456": {
  "user_id": "123456",
  "role_id": 1
}

```

on a result without user ids it returns
```
[]
```

it should return
```
{}
```

**Comment by timecamp** [comment]
Hi, sorry for late response, we will work on this

**Comment by timecamp** [comment]
Hello, this issue is pretty old, we will close it. But if it is still happening, please reopen.
