### ISSUE TITLE
\u0000 added to values

### ISSUE THREAD

**Issue by junaid-anwar** [timecamp/timecamp-api#28]
Almost all the task properties has the null character "\u0000" prepended to the value causing the parsing/deserialization to fail. It was working fine till yesterday. Please see the task output below.

**{
    "task_id": "\u00005952121",
    "parent_id": "\u00005943227",
    "assigned_by": "\u0000001116",
    "name": "\u0000oding",
    "external_task_id": {
        "users": {}
    },
    "external_parent_id": {
        "users": {}
    },
    "level": "\u0000",
    "archived": "\u0000",
    "color": "\u000034C644",
    "tags": {
        "users": {}
    },
    "budgeted": "\u0000",
    "budget_unit": "\u0000ours",
    "root_group_id": "\u00002539",
    "billable": "\u0000",
    "note": {
        "users": {}
    },
    "public_hash": {
        "users": {}
    },
    "add_date": "\u0000017-07-05 23:42:51",
    "modify_time": {
        "users": {}
    },
    "users": {
        "users": {}
    },
    "perms": {
        "1": 0,
        "2": 0,
        "3": 2,
        "5": 0,
        "6": 0,
        "7": 0,
        "users": {}
    },
    "user_access_type": 2
}**

**Comment by jolszak** [comment]
@junaid-anwar can you please retry now? we've released a quick fix. let us know if it works as expected now.

**Comment by junaid-anwar** [comment]
@jolszak The issue seems to be resolved and everything is working as expected. Thanks for the fix.
